# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hauptdialog.ui'
#
# Created: Fri Dec 27 23:29:01 2013
#      by: PyQt5 UI code generator 5.1.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HauptDialog(object):
    def setupUi(self, HauptDialog):
        HauptDialog.setObjectName("HauptDialog")
        HauptDialog.resize(520, 511)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(HauptDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(HauptDialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.vorname = QtWidgets.QLineEdit(self.groupBox)
        self.vorname.setObjectName("vorname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.vorname)
        self.nachname = QtWidgets.QLineEdit(self.groupBox)
        self.nachname.setObjectName("nachname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nachname)
        self.geburtsdatum = QtWidgets.QDateEdit(self.groupBox)
        self.geburtsdatum.setObjectName("geburtsdatum")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.geburtsdatum)
        self.adresse = QtWidgets.QTextEdit(self.groupBox)
        self.adresse.setObjectName("adresse")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.adresse)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(HauptDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.agb = QtWidgets.QCheckBox(self.groupBox_2)
        self.agb.setObjectName("agb")
        self.verticalLayout.addWidget(self.agb)
        self.newsletter = QtWidgets.QCheckBox(self.groupBox_2)
        self.newsletter.setObjectName("newsletter")
        self.verticalLayout.addWidget(self.newsletter)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonOk = QtWidgets.QPushButton(HauptDialog)
        self.buttonOk.setDefault(True)
        self.buttonOk.setObjectName("buttonOk")
        self.horizontalLayout.addWidget(self.buttonOk)
        self.buttonAbbrechen = QtWidgets.QPushButton(HauptDialog)
        self.buttonAbbrechen.setObjectName("buttonAbbrechen")
        self.horizontalLayout.addWidget(self.buttonAbbrechen)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.vorname)
        self.label_3.setBuddy(self.adresse)
        self.label_2.setBuddy(self.geburtsdatum)
        self.label_4.setBuddy(self.nachname)

        self.retranslateUi(HauptDialog)
        QtCore.QMetaObject.connectSlotsByName(HauptDialog)
        HauptDialog.setTabOrder(self.vorname, self.nachname)
        HauptDialog.setTabOrder(self.nachname, self.geburtsdatum)
        HauptDialog.setTabOrder(self.geburtsdatum, self.adresse)
        HauptDialog.setTabOrder(self.adresse, self.agb)
        HauptDialog.setTabOrder(self.agb, self.newsletter)
        HauptDialog.setTabOrder(self.newsletter, self.buttonOk)
        HauptDialog.setTabOrder(self.buttonOk, self.buttonAbbrechen)

    def retranslateUi(self, HauptDialog):
        _translate = QtCore.QCoreApplication.translate
        HauptDialog.setWindowTitle(_translate("HauptDialog", "Dialog"))
        self.groupBox.setTitle(_translate("HauptDialog", "Persönliche Daten"))
        self.label.setText(_translate("HauptDialog", "Name"))
        self.label_3.setText(_translate("HauptDialog", "Adresse"))
        self.label_2.setText(_translate("HauptDialog", "Geburtsdatum"))
        self.label_4.setText(_translate("HauptDialog", "Nachname"))
        self.groupBox_2.setTitle(_translate("HauptDialog", "Weitere Angaben"))
        self.agb.setText(_translate("HauptDialog", "AGB Gelesen"))
        self.newsletter.setText(_translate("HauptDialog", "Katalog besellen"))
        self.buttonOk.setText(_translate("HauptDialog", "&Ok"))
        self.buttonAbbrechen.setText(_translate("HauptDialog", "Abbrechen"))

