# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hauptdialog.ui'
#
# Created: Tue Aug 09 08:52:23 2011
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_HauptDialog(object):
    def setupUi(self, HauptDialog):
        HauptDialog.setObjectName("HauptDialog")
        HauptDialog.resize(520, 511)
        self.verticalLayout_2 = QtGui.QVBoxLayout(HauptDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(HauptDialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.vorname = QtGui.QLineEdit(self.groupBox)
        self.vorname.setObjectName("vorname")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.vorname)
        self.nachname = QtGui.QLineEdit(self.groupBox)
        self.nachname.setObjectName("nachname")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.nachname)
        self.geburtsdatum = QtGui.QDateEdit(self.groupBox)
        self.geburtsdatum.setObjectName("geburtsdatum")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.geburtsdatum)
        self.adresse = QtGui.QTextEdit(self.groupBox)
        self.adresse.setObjectName("adresse")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.adresse)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(HauptDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.agb = QtGui.QCheckBox(self.groupBox_2)
        self.agb.setObjectName("agb")
        self.verticalLayout.addWidget(self.agb)
        self.newsletter = QtGui.QCheckBox(self.groupBox_2)
        self.newsletter.setObjectName("newsletter")
        self.verticalLayout.addWidget(self.newsletter)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonOk = QtGui.QPushButton(HauptDialog)
        self.buttonOk.setDefault(True)
        self.buttonOk.setObjectName("buttonOk")
        self.horizontalLayout.addWidget(self.buttonOk)
        self.buttonAbbrechen = QtGui.QPushButton(HauptDialog)
        self.buttonAbbrechen.setObjectName("buttonAbbrechen")
        self.horizontalLayout.addWidget(self.buttonAbbrechen)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.vorname)
        self.label_3.setBuddy(self.adresse)
        self.label_2.setBuddy(self.geburtsdatum)
        self.label_4.setBuddy(self.nachname)

        self.retranslateUi(HauptDialog)
        QtCore.QMetaObject.connectSlotsByName(HauptDialog)
        HauptDialog.setTabOrder(self.vorname, self.nachname)
        HauptDialog.setTabOrder(self.nachname, self.geburtsdatum)
        HauptDialog.setTabOrder(self.geburtsdatum, self.adresse)
        HauptDialog.setTabOrder(self.adresse, self.agb)
        HauptDialog.setTabOrder(self.agb, self.newsletter)
        HauptDialog.setTabOrder(self.newsletter, self.buttonOk)
        HauptDialog.setTabOrder(self.buttonOk, self.buttonAbbrechen)

    def retranslateUi(self, HauptDialog):
        HauptDialog.setWindowTitle(QtGui.QApplication.translate("HauptDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("HauptDialog", "Persönliche Daten", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HauptDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("HauptDialog", "Adresse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HauptDialog", "Geburtsdatum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("HauptDialog", "Nachname", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("HauptDialog", "Weitere Angaben", None, QtGui.QApplication.UnicodeUTF8))
        self.agb.setText(QtGui.QApplication.translate("HauptDialog", "AGB Gelesen", None, QtGui.QApplication.UnicodeUTF8))
        self.newsletter.setText(QtGui.QApplication.translate("HauptDialog", "Katalog besellen", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonOk.setText(QtGui.QApplication.translate("HauptDialog", "&Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAbbrechen.setText(QtGui.QApplication.translate("HauptDialog", "Abbrechen", None, QtGui.QApplication.UnicodeUTF8))

